### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by varlevi** [varlevi/the_shade_generator#12]
I think it would be a great feature, especially since users could be viewing bright colors and want to see the contrast.

I think a button that toggles from light to dark mode would be very helpful. This would not only change the background color, but the text color as well.

As long as this feature is programmed well, I cannot think of any problems that could arise.

**Comment by wajeehsheikh** [comment]
Hi,
I would like to take a shot at this.
Thank you,
Waj

**Comment by varlevi** [comment]
I am closing this issue thank you to everyone who contributed! The feature with be included in v0.5.
