### ISSUE TITLE
Input Fields Are Too Small

### ISSUE THREAD

**Issue by varlevi** [varlevi/the_shade_generator#13]
**Describe the bug**
The input fields are too small

**Expected behavior**
The user expects a larger input field for easier use.

**Desktop (please complete the following information):**
 - OS: ALL
 - Browser: ALL
 - Versions: ALL

**Smartphone (please complete the following information):**
I have not tested this on a smartphone, but iPad screens also show that the input is too small.

**Additional context**
This is probably a simple CSS fix.

**Comment by varlevi** [comment]
I've tried fixing this in the CSS file, but changes are not being implemented to the Github page.

**Comment by wajeehsheikh** [comment]
Hi,
I would like to take a shot at this.
Thank you,
Waj

**Comment by xNocken** [comment]
i made a PR for this
