### ISSUE TITLE
feature: layout shades in rows instead of single column

### ISSUE THREAD

**Issue by cdrani** [varlevi/the_shade_generator#18]
**Describe the solution you'd like**
I think users would love less vertical scrolling and have a better experience with a grid row layout where they could view 3-5 shades per row.

**Comment by varlevi** [comment]
Great idea! In earlier versions I had a two column layout, but cut it because it was causing me some problems. I'll leave it up to you if you want to tackle the problem or not.

**Comment by varlevi** [comment]
Okay. I’m thinking about tackling this, but 
I was wondering if you think it would be better to have multiple rows or multiple columns

**Comment by varlevi** [comment]
Alright. I believe I've fixed this in the 'beta' branch. Check it out to see if it's working correctly.

**Comment by cdrani** [comment]
@varlevi : It has already been merged in, so this issue should be closed now. In [PR 24](https://github.com/varlevi/the_shade_generator/pull/24), I reduced the `.card` margin to fit in 3 cards per row.
