### ISSUE TITLE
When an error occurs, the script keeps going

### ISSUE THREAD

**Issue by varlevi** [varlevi/the_shade_generator#32]
**Describe the bug**
When confronted with bad inputs, the script gives the user an alert, and then still tries to output shades.

**To Reproduce**
1. Open up the website.
2. Input some bad inputs (> 255, or strings).
3. Accept error.
4. Look at the shades output.

**Expected behavior**
An error alert, and no output.

**Comment by cdrani** [comment]
@varlevi : I believe I fixed this in #29 https://github.com/varlevi/the_shade_generator/blob/57ca9bb34b06bf4124cef4659935e369028e14ee/js/script.js#L114

```js
    // User input validation
    const allValid = valuesValidators(colors, values);
    if (!allValid) {
        showAlert();
        setContent();
        return;
    }
```

**Comment by varlevi** [comment]
Great! I'll close this once we merge #29 in.

**Comment by varlevi** [comment]
Would you mind creating a separate pull request for this, so I can implement it ASAP? I noticed a few issues in #29, but want to get this part in quickly because it's a bug.
