### ISSUE TITLE
"Undefined"

### ISSUE THREAD

**Issue by varlevi** [varlevi/the_shade_generator#6]
Before the Base Color is shown, the word undefined is displayed.
![Screen Shot 2019-07-24 at 11 22 58 AM](https://user-images.githubusercontent.com/53223556/61810732-7e630980-ae05-11e9-873b-2e34e974ebd7.png)

**Comment by patrickblackjr** [comment]
I'll take care of it. I think the next step is to use a templating language (check out Vue.js) to help have better control over the display.

But I'll fix it in the meantime.
