### ISSUE TITLE
Create a form field to replace the alerts.

### ISSUE THREAD

**Issue by patrickblackjr** [varlevi/the_shade_generator#9]
Create a form to replace the JS prompts for better UX.

**Comment by varlevi** [comment]
Hmm... Not quite sure what to do here. The DOM is probably the way to go.

**Comment by patrickblackjr** [comment]
https://vuejs.org/

**Comment by patrickblackjr** [comment]
Or if you wanted to go simpler: https://handlebarsjs.com/

**Comment by varlevi** [comment]
I'm thinking I'll use Vue (it definitely seems to have better documentation), but have to learn a little more before I change this project.

**Comment by varlevi** [comment]
This issue is mostly resolved. Check out the form-field branch to check for any bugs and prepare to add this feature to the next stable release.
